"""Builds a crop's training manifest from its raw datasets.

Usage (from the ml/ folder):

    .venv/Scripts/python -m agrilink_ml.prepare --crop cassava \
        --source kaggle-cassava-2020=C:/path/to/cassava-leaf-disease-classification.zip

Writes manifests/<crop>.csv (one row per usable image, with its class and split) and
manifests/<crop>_summary.md. Both are committed, so every training run - local, Kaggle or Colab -
uses exactly the same split.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from . import MANIFESTS_DIR
from .dedupe import difference_hash, group_near_duplicates
from .labels import CropLabels, load_crop_labels
from .sources import SOURCE_ADAPTERS, DatasetReader
from .split import TEST, TRAIN, VALIDATION, assign_splits

MANIFEST_COLUMNS = ["source", "path", "label_id", "label_key", "split", "group_id", "sha1", "dhash"]


@dataclass
class ManifestRow:
    source: str
    path: str
    label_id: int
    label_key: str
    sha1: str
    dhash: int
    group_id: int = -1
    split: str = ""


def collect_rows(labels: CropLabels, sources: dict[str, Path], log=print) -> tuple[list[ManifestRow], list[str]]:
    rows: list[ManifestRow] = []
    unreadable: list[str] = []

    for source, root in sources.items():
        if source not in SOURCE_ADAPTERS:
            raise ValueError(f"No adapter for source '{source}'. Known: {sorted(SOURCE_ADAPTERS)}.")

        with DatasetReader(root) as reader:
            images = SOURCE_ADAPTERS[source](reader)
            log(f"{source}: {len(images)} images listed; hashing...")
            for index, image in enumerate(images, start=1):
                label_class = labels.map_source_label(source, image.source_label)
                content = reader.read_bytes(image.path)
                try:
                    dhash = difference_hash(content)
                except Exception:  # corrupt or unsupported file — excluded and reported
                    unreadable.append(f"{source}:{image.path}")
                    continue

                rows.append(ManifestRow(
                    source=source,
                    path=image.path,
                    label_id=label_class.id,
                    label_key=label_class.key,
                    sha1=hashlib.sha1(content).hexdigest(),
                    dhash=dhash,
                ))
                if index % 2000 == 0:
                    log(f"  {index}/{len(images)}")

    return rows, unreadable


def conflicting_label_groups(rows: list[ManifestRow]) -> dict[int, set[str]]:
    """Groups of (near-)identical photos that carry different labels — likely label noise."""
    keys_by_group: dict[int, set[str]] = {}
    for row in rows:
        keys_by_group.setdefault(row.group_id, set()).add(row.label_key)
    return {group: keys for group, keys in keys_by_group.items() if len(keys) > 1}


def write_manifest(rows: list[ManifestRow], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file, lineterminator="\n")
        writer.writerow(MANIFEST_COLUMNS)
        for row in sorted(rows, key=lambda r: (r.source, r.path)):
            writer.writerow([row.source, row.path, row.label_id, row.label_key, row.split,
                             row.group_id, row.sha1, f"{row.dhash:016x}"])


def build_summary(labels: CropLabels, rows: list[ManifestRow], unreadable: list[str],
                  max_distance: int, seed: int) -> str:
    splits = [TRAIN, VALIDATION, TEST]
    counts = Counter((row.label_key, row.split) for row in rows)
    group_sizes = Counter(row.group_id for row in rows)
    duplicate_groups = [size for size in group_sizes.values() if size > 1]
    exact_duplicates = len(rows) - len({row.sha1 for row in rows})
    conflicts = conflicting_label_groups(rows)

    lines = [
        f"# {labels.crop} dataset summary",
        "",
        f"Generated by `agrilink_ml.prepare` - label file version {labels.version}, seed {seed}, "
        f"near-duplicate distance <= {max_distance} bits.",
        "",
        "| Class | " + " | ".join(splits) + " | Total |",
        "|---|" + "---:|" * (len(splits) + 1),
    ]
    for label_class in labels.classes:
        per_split = [counts[(label_class.key, split)] for split in splits]
        lines.append(f"| {label_class.name} | " + " | ".join(map(str, per_split)) + f" | {sum(per_split)} |")
    split_totals = [sum(counts[(c.key, split)] for c in labels.classes) for split in splits]
    lines.append("| **Total** | " + " | ".join(map(str, split_totals)) + f" | {len(rows)} |")

    lines += [
        "",
        "## Data quality",
        "",
        f"- Unreadable images excluded: {len(unreadable)}",
        f"- Exact duplicate files (same bytes): {exact_duplicates}",
        f"- Near-duplicate groups: {len(duplicate_groups)} groups covering {sum(duplicate_groups)} images "
        f"(largest group: {max(group_sizes.values(), default=0)} images). Each group is kept in a single split.",
        f"- Near-duplicate groups with conflicting labels: {len(conflicts)}",
    ]
    for group, keys in sorted(conflicts.items())[:20]:
        paths = sorted(row.path for row in rows if row.group_id == group)
        lines.append(f"  - group {group}: {', '.join(sorted(keys))} - {', '.join(paths)}")
    if len(conflicts) > 20:
        lines.append(f"  - ...and {len(conflicts) - 20} more (see group_id in the manifest)")
    if unreadable:
        lines += ["", "## Unreadable images", ""] + [f"- {path}" for path in unreadable]

    return "\n".join(lines) + "\n"


def parse_sources(values: list[str]) -> dict[str, Path]:
    sources: dict[str, Path] = {}
    for value in values:
        name, separator, path = value.partition("=")
        if not separator or not name or not path:
            raise argparse.ArgumentTypeError(f"--source must look like name=path, got '{value}'.")
        sources[name] = Path(path)
    return sources


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--crop", required=True, help="Crop whose label file to use, e.g. cassava.")
    parser.add_argument("--source", action="append", required=True, metavar="NAME=PATH",
                        help="A raw dataset: adapter name and its zip or extracted folder. Repeatable.")
    # 2 bits catches resized or recompressed copies. On the Cassava field photos, pairs at 3-6 bits
    # were checked by eye and were different plants, and 8+ bits chains unrelated photos into groups
    # of hundreds — so re-check visually before loosening this for a new dataset.
    parser.add_argument("--near-duplicate-distance", type=int, default=2,
                        help="Max differing dHash bits for two images to count as near-duplicates.")
    parser.add_argument("--seed", type=int, default=13)
    parser.add_argument("--output-dir", type=Path, default=MANIFESTS_DIR)
    args = parser.parse_args(argv)

    labels = load_crop_labels(args.crop)
    rows, unreadable = collect_rows(labels, parse_sources(args.source))
    if not rows:
        print("No usable images found.", file=sys.stderr)
        return 1

    print(f"Grouping near-duplicates among {len(rows)} images...")
    group_ids = group_near_duplicates([row.dhash for row in rows], args.near_duplicate_distance)
    splits = assign_splits([row.label_id for row in rows], group_ids, seed=args.seed)
    for row, group_id, split in zip(rows, group_ids, splits):
        row.group_id, row.split = group_id, split

    crop = args.crop.lower()
    write_manifest(rows, args.output_dir / f"{crop}.csv")
    summary = build_summary(labels, rows, unreadable, args.near_duplicate_distance, args.seed)
    (args.output_dir / f"{crop}_summary.md").write_text(summary, encoding="utf-8")
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
