using System.Text.RegularExpressions;

namespace AgriLink.API.Services.Images;

// Development fallback used when Cloudinary credentials are not configured. Files live on the API
// server's own disk, so they do not survive a redeploy to most hosts — not for production use.
public partial class LocalImageStorageService : IImageStorageService
{
    private const string KeyPrefix = "issues/";

    private readonly string _root;

    public LocalImageStorageService(string rootDirectory)
    {
        _root = Path.GetFullPath(rootDirectory);
    }

    public async Task<string> SaveAsync(byte[] content, string contentType, CancellationToken cancellationToken)
    {
        var key = $"{KeyPrefix}{Guid.NewGuid():N}{ExtensionFor(contentType)}";
        var path = ResolvePath(key);

        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            await File.WriteAllBytesAsync(path, content, cancellationToken);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new ImageStorageException("Saving the photo to local storage failed.", ex);
        }

        return key;
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken)
    {
        var path = ResolvePath(storageKey);

        try
        {
            File.Delete(path); // no-op when the file is already gone
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new ImageStorageException("Deleting the photo from local storage failed.", ex);
        }

        return Task.CompletedTask;
    }

    // Keys are only ever generated by SaveAsync, but a key read back from the database is still
    // checked against that exact shape before it becomes a file path, so no stored value can
    // point outside the storage root.
    private string ResolvePath(string storageKey)
    {
        if (!StorageKeyPattern().IsMatch(storageKey))
        {
            throw new ArgumentException("Not a valid local image storage key.", nameof(storageKey));
        }

        return Path.Combine(_root, storageKey.Replace('/', Path.DirectorySeparatorChar));
    }

    private static string ExtensionFor(string contentType) => contentType switch
    {
        "image/jpeg" => ".jpg",
        "image/png" => ".png",
        "image/webp" => ".webp",
        _ => throw new ArgumentException($"Unsupported content type '{contentType}'.", nameof(contentType)),
    };

    [GeneratedRegex(@"^issues/[0-9a-f]{32}\.(jpg|png|webp)$")]
    private static partial Regex StorageKeyPattern();
}
